tinyMCE.addI18n('pt.table_dlg',{
general_tab:"Geral",
advanced_tab:"Avançado",
general_props:"Propriedades gerais",
advanced_props:"Propriedades avançadas",
rowtype:"Linha na parte da tabela",
title:"Inserir/modificar tabela",
width:"Largura",
height:"Altura",
cols:"Colunas",
rows:"Linhas",
cellspacing:"Espaçamento da célula",
cellpadding:"Margem interna da célula",
border:"Borda",
align:"Alinhamento",
align_default:"Padrão",
align_left:"Esquerda",
align_right:"Direita",
align_middle:"Centro",
row_title:"Propriedade de linhas da tabela",
cell_title:"Propriedade de células da tabela",
cell_type:"Tipo de célula",
valign:"Alinhamento vertical",
align_top:"Topo",
align_bottom:"Base", // bottom
bordercolor:"Cor da borda",
bgcolor:"Cor de fundo",
merge_cells_title:"Mesclar células da tabela",
id:"Id",
style:"Estilo",
langdir:"Direção da linguagem",
langcode:"Código da linguagem",
mime:"Tipo MIME do arquivo",
ltr:"Esquerda para direita",
rtl:"Direita para esquerda",
bgimage:"Imagem de fundo",
summary:"Sumário",
td:"Dados",
th:"Cabeçalho",
cell_cell:"Atualizar célula atual",
cell_row:"Atualizar célular desta linha",
cell_all:"Atualizar células desta tabela",
row_row:"Atualizar linha atual",
row_odd:"Atualizar linhas ímpares na tabela",
row_even:"Atualizar linhas pares na tabela",
row_all:"Atualizar todas as linhas na tabela",
thead:"Cabeçalho da tabela",
tbody:"Corpo da tabela",
tfoot:"Rodapé da tabela",
scope:"Escopo",
rowgroup:"Grupo de linhas",
colgroup:"Grupo de colunas",
col_limit:"Você excedeu o número máximo de colunas de {$cols}.",
row_limit:"Você excedeu o número máximo de linhas de {$rows}.",
cell_limit:"Você excedeu o número máximo de células de {$cells}.",
missing_scope:"Você tem certeza que deseja continuar sem especificar um escopo para o cabeçalho desta célula? Sem isto pode ser difícil de alguns usuários de deficiências visuais entenderem o conteúdo ou dados mostrados na tabela.",
caption:"Título da tabela",
frame:"Frame",
frame_none:"none",
frame_groups:"grupos",
frame_rows:"linhas",
frame_cols:"colunas",
frame_all:"todos",
rules:"Regras",
rules_void:"evitar",
rules_above:"acima",
rules_below:"abaixo",
rules_hsides:"hsides",
rules_lhs:"lhs",
rules_rhs:"rhs",
rules_vsides:"vsides",
rules_box:"caixa",
rules_border:"borda"
});